/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itlijunjie_andrioddemo1_ndk_NDKTest */

#ifndef _Included_com_itlijunjie_andrioddemo1_ndk_NDKTest
#define _Included_com_itlijunjie_andrioddemo1_ndk_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itlijunjie_andrioddemo1_ndk_NDKTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itlijunjie_andrioddemo1_ndk_NDKTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
